"""Strict, versioned YAML interchange for Alert Manager.

This module deliberately only understands Alert Manager's own comparison rule
model.  It does not interpret Home Assistant automation conditions.
"""

from __future__ import annotations

from collections.abc import Mapping
from copy import deepcopy
from typing import Any

import yaml

from .const import CATEGORIES, DEFAULT_CONFIG
from .models import Rule
from .validation import validate_config, validate_rule_payload

FORMAT_VERSION = 1
MAX_YAML_SIZE = 1_000_000

_RULE_YAML_KEYS = {
    "id",
    "name",
    "enabled",
    "entity_ids",
    "source",
    "attribute",
    "operator",
    "value",
    "duration",
    "message",
    "condition_template",
}
_CONFIG_YAML_KEY_ORDER = (
    "monitoring_enabled",
    "coherence_schedule",
    "global_delay",
    "pending_display_delay",
    "excluded_labels",
    "excluded_entities",
    "excluded_devices",
    "entity_delays",
    "automatic",
)
_CONFIG_YAML_KEYS = set(_CONFIG_YAML_KEY_ORDER)


class _UniqueKeyLoader(yaml.SafeLoader):
    """Safe loader which rejects duplicate mapping keys instead of overwriting."""


def _construct_mapping(
    loader: _UniqueKeyLoader, node: yaml.nodes.MappingNode, deep: bool = False
) -> dict[Any, Any]:
    """Construct mappings without accepting duplicate keys."""
    mapping: dict[Any, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        try:
            duplicate = key in mapping
        except TypeError as err:
            raise ValueError("YAML mapping keys must be scalar") from err
        if duplicate:
            raise ValueError(f"Duplicate YAML key: {key}")
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


_UniqueKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _construct_mapping
)


def _load_yaml(raw_yaml: Any, *, description: str) -> Any:
    """Parse an UTF-8 YAML string and turn parser errors into API errors."""
    if not isinstance(raw_yaml, str):
        raise ValueError(f"{description} YAML must be text")
    try:
        encoded_size = len(raw_yaml.encode("utf-8"))
    except UnicodeEncodeError as err:
        raise ValueError(f"{description} YAML must contain valid Unicode") from err
    if encoded_size > MAX_YAML_SIZE:
        raise ValueError(f"{description} YAML must not exceed {MAX_YAML_SIZE} bytes")
    try:
        loaded = yaml.load(raw_yaml, Loader=_UniqueKeyLoader)
    except (yaml.YAMLError, ValueError) as err:
        raise ValueError(f"Invalid YAML: {err}") from err
    if loaded is None:
        raise ValueError(f"{description} YAML must not be empty")
    return loaded


def _reject_unknown(data: Mapping[str, Any], allowed: set[str], *, prefix: str) -> None:
    """Reject unknown fields with one concise, stable error."""
    invalid = [key for key in data if not isinstance(key, str)]
    if invalid:
        raise ValueError(f"Invalid {prefix} field name: {invalid[0]!r}")
    unknown = set(data) - allowed
    if unknown:
        raise ValueError(f"Unknown {prefix} field: {sorted(unknown)[0]}")


def rule_to_yaml_data(
    rule: Rule | Mapping[str, Any], *, include_id: bool = False
) -> dict[str, Any]:
    """Return the documented rule shape in a stable human-readable order."""
    data = rule.as_dict() if isinstance(rule, Rule) else dict(rule)
    result: dict[str, Any] = {
        "name": data.get("name"),
        "enabled": data.get("enabled", True),
        "entity_ids": data.get("entity_ids"),
        "source": data.get("source", "state"),
    }
    if result["source"] == "attribute":
        result["attribute"] = data.get("attribute")
    result.update(
        {
            "operator": data.get("operator"),
            "value": data.get("value"),
            "duration": data.get("duration"),
            "message": data.get("message"),
            "condition_template": data.get("condition_template"),
        }
    )
    if include_id:
        return {"id": data.get("id"), **result}
    return result


def dump_rule_yaml(rule: Rule | Mapping[str, Any]) -> str:
    """Serialize one editable rule, intentionally omitting its immutable id."""
    return _dump_yaml(rule_to_yaml_data(rule))


def parse_rule_yaml(raw_yaml: Any, *, rule_id: str | None = None) -> Rule:
    """Parse and validate the YAML representation of one rule.

    Existing rule ids are owned by the URL/WebSocket target and never edited in
    the YAML editor.  An id may be present only when it exactly matches that
    target, which makes pasted exported rules safe to inspect as well.
    """
    data = _load_yaml(raw_yaml, description="Rule")
    if not isinstance(data, dict):
        raise ValueError("Rule YAML root must be an object")
    _reject_unknown(data, _RULE_YAML_KEYS, prefix="rule")
    if rule_id is None:
        if "id" in data:
            raise ValueError("Rule id is generated by the backend")
        try:
            return validate_rule_payload(data)
        except TypeError as err:
            raise ValueError(f"Invalid rule: {err}") from err
    supplied_id = data.pop("id", rule_id)
    if supplied_id != rule_id:
        raise ValueError("Rule id is immutable")
    try:
        return validate_rule_payload(data, rule_id=rule_id)
    except TypeError as err:
        raise ValueError(f"Invalid rule: {err}") from err


def dump_config_yaml(config: Mapping[str, Any]) -> str:
    """Serialize all persistent configuration, excluding runtime alert data."""
    normalized = validate_config(dict(config))
    config_data = {key: deepcopy(normalized[key]) for key in _CONFIG_YAML_KEY_ORDER}
    rules = [rule_to_yaml_data(rule) for rule in normalized["rules"]]
    return _dump_yaml(
        {
            "version": FORMAT_VERSION,
            "config": config_data,
            "rules": rules,
        }
    )


def parse_config_yaml(raw_yaml: Any) -> dict[str, Any]:
    """Parse one complete configuration import with an intentionally strict schema."""
    document = _load_yaml(raw_yaml, description="Configuration")
    if not isinstance(document, dict):
        raise ValueError("Configuration YAML root must be an object")
    _reject_unknown(document, {"version", "config", "rules"}, prefix="configuration")
    if document.get("version") != FORMAT_VERSION:
        raise ValueError(
            f"Unsupported configuration format version: {document.get('version')}"
        )
    config = document.get("config")
    if not isinstance(config, dict):
        raise ValueError("Configuration config must be an object")
    _reject_unknown(
        config,
        _CONFIG_YAML_KEYS | {"active_display_delay"},
        prefix="config",
    )
    if "active_display_delay" in config:
        if "pending_display_delay" in config:
            raise ValueError(
                "config cannot contain both active_display_delay and "
                "pending_display_delay"
            )
        config = dict(config)
        config["pending_display_delay"] = config.pop("active_display_delay")
    # V1.5 exports predate the persistent category switch. They remain safe to
    # import and default monitoring to enabled.
    missing_config = (
        _CONFIG_YAML_KEYS
        - {
            "monitoring_enabled",
            "coherence_schedule",
            "pending_display_delay",
        }
        - set(config)
    )
    if missing_config:
        raise ValueError(f"Missing config field: {sorted(missing_config)[0]}")
    automatic = config.get("automatic")
    if not isinstance(automatic, dict):
        raise ValueError("config.automatic must be an object")
    if set(automatic) != set(CATEGORIES):
        missing = set(CATEGORIES) - set(automatic)
        unknown = set(automatic) - set(CATEGORIES)
        field = sorted(missing or unknown)[0]
        raise ValueError(f"Invalid automatic pack configuration: {field}")
    for category in CATEGORIES:
        expected_fields = set(DEFAULT_CONFIG["automatic"][category])
        actual_fields = (
            set(automatic[category]) if isinstance(automatic[category], dict) else set()
        )
        if actual_fields != expected_fields:
            missing = expected_fields - actual_fields
            unknown = actual_fields - expected_fields
            field = sorted(missing or unknown)[0]
            raise ValueError(f"Invalid automatic.{category} field: {field}")

    rules = document.get("rules")
    if not isinstance(rules, list):
        raise ValueError("Configuration rules must be a list")
    normalized_rules: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    for index, raw_rule in enumerate(rules):
        if not isinstance(raw_rule, dict):
            raise ValueError(f"rules[{index}] must be an object")
        _reject_unknown(raw_rule, _RULE_YAML_KEYS, prefix=f"rules[{index}]")
        rule_id = raw_rule.get("id")
        if rule_id is None:
            try:
                rule = validate_rule_payload(dict(raw_rule))
            except TypeError as err:
                raise ValueError(f"Invalid rules[{index}]: {err}") from err
            if rule.id in seen_ids:
                raise ValueError(f"Duplicate rule id: {rule.id}")
            seen_ids.add(rule.id)
            normalized_rules.append(rule.as_dict())
            continue
        if not isinstance(rule_id, str) or not rule_id:
            raise ValueError(f"rules[{index}].id must be a non-empty string")
        if rule_id in seen_ids:
            raise ValueError(f"Duplicate rule id: {rule_id}")
        seen_ids.add(rule_id)
        try:
            rule = validate_rule_payload(dict(raw_rule), rule_id=rule_id)
        except TypeError as err:
            raise ValueError(f"Invalid rules[{index}]: {err}") from err
        normalized_rules.append(rule.as_dict())

    candidate = {**deepcopy(config), "rules": normalized_rules}
    return validate_config(candidate)


def import_summary(config: Mapping[str, Any]) -> dict[str, Any]:
    """Build the small, safe import preview presented by the panel."""
    automatic = config["automatic"]
    return {
        "rules": len(config["rules"]),
        "enabled_packs": sum(1 for pack in automatic.values() if pack["enabled"]),
        "entity_delays": len(config["entity_delays"]),
        "warnings": [],
    }


def _dump_yaml(data: Any) -> str:
    """Produce deterministic UTF-8 compatible YAML without aliases or sorting."""
    return yaml.safe_dump(
        data,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=88,
    )
